<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Description</title>
  <style>
    table td,
    table th {
    border: 1px rgb(148, 148, 148) solid;
    padding: 10px;
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
  }
  </style>
</head>
<body>
  <h1>Description</h1>
  <div>
  <table>
    <thead>
    <tr>
    <th>Title</th>
    <th>descricao</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->view->data as $key => $value){ ?>
      <tr>
          <td><?=$value['titulo']?></td>
          <td><?=$value['descricao']?></td>
      </tr>
    <?php } ?>
    </tbody></table> 
  </div>
</body>
</html>