<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    table td,
    table th {
    border: 1px rgb(148, 148, 148) solid;
    padding: 10px;
    text-align: center;
    font-family: Arial, Helvetica, sans-serif;
  }
  </style>
  <title>Home</title>
</head>
<body>
<h1>Index</h1>

  
    <div>
      <table>
        <thead>
        <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Birth Date</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($this->view->data as $key => $value){?>
          <tr>
            <td><?=$value['id']?></td>
            <td><?=$value['name']?></td>
            <td><?=$value['email']?></td>
            <td><?=$value['date_of_birth']?></td>  
          </tr>
        <?php }?>
        </tbody>
      </table>
    </div>

</body>
</html>